/*
 * MCP tool for Ghidra script management.
 *
 * Actions:
 * - list:   List all scripts in the user scripts directory with metadata
 * - read:   Return the source of a named script
 * - write:  Write (create or overwrite) a script file
 * - run:    Execute a named script in the current Ghidra context
 * - delete: Delete a named script file
 *
 * Scripts written here appear in Ghidra's Script Manager after clicking Refresh.
 * Scripts must conform to GhidraScript conventions (use currentProgram, monitor, etc.).
 * Supports iterating and calling existing scripts, not just ones generated by MCP.
 */
package ghidrassistmcp.tools;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import generic.jar.ResourceFile;
import ghidra.app.script.GhidraScript;
import ghidra.app.script.GhidraScriptProvider;
import ghidra.app.script.GhidraScriptUtil;
import ghidra.app.script.GhidraState;
import ghidra.app.script.ScriptControls;
import ghidra.program.model.listing.Program;
import ghidra.util.Msg;
import ghidra.util.task.TaskMonitor;
import ghidrassistmcp.GhidrAssistMCPBackend;
import ghidrassistmcp.GhidrAssistMCPPlugin;
import ghidrassistmcp.McpTool;
import io.modelcontextprotocol.spec.McpSchema;

public class ScriptsTool implements McpTool {

    @Override
    public String getName() { return "scripts"; }

    @Override
    public String getDescription() {
        return """
            Manage and run Ghidra scripts. Scripts live in ~/ghidra_scripts and appear \
            in Ghidra's Script Manager after clicking Refresh (green arrow).

            Actions:
              list   — List all .py/.java scripts with name, category, description, and path
                        Optional filter: {"pattern": "actor"} to match filename substring
              read   — Return the full source of a named script: {"name": "FindActors.py"}
              write  — Create or overwrite a script: {"name": "...", "code": "...", \
                        "category": "MCP", "description": "..."}
                        @category and @description metadata prepended automatically if absent.
                        Script appears in Script Manager after Refresh.
              run    — Execute a script in the current Ghidra context: {"name": "FindActors.py"}
                        Output is captured and returned. Script has access to currentProgram, \
                        monitor, state. Equivalent to running from Script Manager.
              delete — Delete a script file: {"name": "FindActors.py"}

            Workflow — LLM as RE tool generator:
              1. `scripts list` to see what already exists (GhidrOllama, importers, etc.)
              2. `scripts read` to inspect an existing script before running or modifying it
              3. Prototype logic via eval_python (interactive, ephemeral)
              4. `scripts write` to save working code as a permanent Ghidra tool
              5. `scripts run` to execute any script from MCP
              6. Result: reusable tools that persist beyond the MCP session
            """;
    }

    @Override
    public McpSchema.JsonSchema getInputSchema() {
        return new McpSchema.JsonSchema("object",
            Map.of(
                "action", Map.of(
                    "type", "string",
                    "enum", List.of("list", "read", "write", "run", "delete"),
                    "description", "Action to perform"
                ),
                "name", Map.of(
                    "type", "string",
                    "description", "Script filename (e.g. 'FindActors.py'). .py extension added if omitted."
                ),
                "code", Map.of(
                    "type", "string",
                    "description", "Script source code (for write action)"
                ),
                "category", Map.of(
                    "type", "string",
                    "description", "Script Manager category (for write action, default: MCP)"
                ),
                "description", Map.of(
                    "type", "string",
                    "description", "Short description shown in Script Manager (for write action)"
                ),
                "pattern", Map.of(
                    "type", "string",
                    "description", "Filename substring filter (for list action)"
                )
            ),
            List.of("action"), null, null, null);
    }

    @Override public boolean isReadOnly() { return false; }
    @Override public boolean isLongRunning() { return false; }
    @Override public boolean isCacheable() { return false; }
    @Override public boolean isDestructive() { return false; }
    @Override public boolean isIdempotent() { return false; }

    @Override
    public McpSchema.CallToolResult execute(Map<String, Object> arguments, Program currentProgram) {
        return McpSchema.CallToolResult.builder()
            .addTextContent("Error: scripts tool requires a backend reference.")
            .build();
    }

    @Override
    public McpSchema.CallToolResult execute(Map<String, Object> arguments, Program currentProgram,
            GhidrAssistMCPBackend backend) {
        String action = (String) arguments.get("action");
        if (action == null) action = "list";

        File scriptsDir = getScriptsDir(backend);

        return switch (action) {
            case "list"   -> doList(scriptsDir, (String) arguments.get("pattern"));
            case "read"   -> doRead(scriptsDir, (String) arguments.get("name"));
            case "write"  -> doWrite(scriptsDir, arguments);
            case "run"    -> doRun(scriptsDir, (String) arguments.get("name"), currentProgram, backend);
            case "delete" -> doDelete(scriptsDir, (String) arguments.get("name"));
            default -> McpSchema.CallToolResult.builder()
                .addTextContent("Unknown action: " + action)
                .build();
        };
    }

    private File getScriptsDir(GhidrAssistMCPBackend backend) {
        // Try GhidraScriptUtil first
        try {
            List<ResourceFile> dirs = GhidraScriptUtil.getScriptSourceDirectories();
            if (dirs != null && !dirs.isEmpty()) {
                File f = dirs.get(0).getFile(false);
                if (f != null && f.isDirectory()) return f;
            }
        } catch (Exception e) {
            Msg.warn(this, "Could not get script dirs from GhidraScriptUtil", e);
        }
        // Fallback: ~/ghidra_scripts
        return new File(System.getProperty("user.home"), "ghidra_scripts");
    }

    private String normalize(String name) {
        if (name == null) return null;
        return (name.endsWith(".py") || name.endsWith(".java")) ? name : name + ".py";
    }

    private McpSchema.CallToolResult doList(File scriptsDir, String pattern) {
        if (!scriptsDir.isDirectory()) {
            return McpSchema.CallToolResult.builder()
                .addTextContent("Scripts directory not found: " + scriptsDir)
                .build();
        }
        File[] files = scriptsDir.listFiles(f ->
            (f.getName().endsWith(".py") || f.getName().endsWith(".java")) &&
            (pattern == null || f.getName().toLowerCase().contains(pattern.toLowerCase()))
        );
        if (files == null || files.length == 0) {
            return McpSchema.CallToolResult.builder()
                .addTextContent("No scripts found in " + scriptsDir +
                    (pattern != null ? " matching '" + pattern + "'" : ""))
                .build();
        }
        Arrays.sort(files);
        StringBuilder sb = new StringBuilder();
        sb.append("Scripts in ").append(scriptsDir).append(" (").append(files.length).append("):\n\n");
        for (File f : files) {
            String[] meta = readScriptMeta(f);
            sb.append(String.format("%-35s  %-20s  %s%n", f.getName(), meta[0], meta[1]));
        }
        return McpSchema.CallToolResult.builder().addTextContent(sb.toString()).build();
    }

    private String[] readScriptMeta(File f) {
        String category = "", description = "";
        try {
            List<String> lines = Files.readAllLines(f.toPath(), StandardCharsets.UTF_8);
            for (String line : lines) {
                if (!line.startsWith("#") && !line.trim().isEmpty()) break;
                if (line.contains("@category"))    category    = line.replaceFirst(".*@category\\s*", "").trim();
                if (line.contains("@description")) description = line.replaceFirst(".*@description\\s*", "").trim();
            }
        } catch (IOException ignored) {}
        return new String[]{category, description};
    }

    private McpSchema.CallToolResult doRead(File scriptsDir, String name) {
        if (name == null) return McpSchema.CallToolResult.builder()
            .addTextContent("'name' parameter required").build();
        File f = new File(scriptsDir, normalize(name));
        if (!f.exists()) return McpSchema.CallToolResult.builder()
            .addTextContent("Script not found: " + f.getAbsolutePath()).build();
        try {
            String content = new String(Files.readAllBytes(f.toPath()), StandardCharsets.UTF_8);
            return McpSchema.CallToolResult.builder()
                .addTextContent("// " + f.getAbsolutePath() + "\n\n" + content)
                .build();
        } catch (IOException e) {
            return McpSchema.CallToolResult.builder()
                .addTextContent("Error reading script: " + e.getMessage()).build();
        }
    }

    private McpSchema.CallToolResult doWrite(File scriptsDir, Map<String, Object> args) {
        String name = normalize((String) args.get("name"));
        String code = (String) args.get("code");
        if (name == null || code == null) return McpSchema.CallToolResult.builder()
            .addTextContent("'name' and 'code' parameters required").build();

        String category = args.getOrDefault("category", "MCP").toString();
        String desc = args.getOrDefault("description", "").toString();

        // Prepend metadata if missing
        StringBuilder header = new StringBuilder();
        if (!code.contains("@category"))    header.append("# @category ").append(category).append("\n");
        if (!desc.isEmpty() && !code.contains("@description"))
            header.append("# @description ").append(desc).append("\n");

        if (!scriptsDir.isDirectory()) scriptsDir.mkdirs();
        File f = new File(scriptsDir, name);
        try {
            Files.write(f.toPath(), (header + code).getBytes(StandardCharsets.UTF_8));
            return McpSchema.CallToolResult.builder()
                .addTextContent("Script written: " + f.getAbsolutePath() +
                    "\nRefresh Script Manager (green arrow) to see it.")
                .build();
        } catch (IOException e) {
            return McpSchema.CallToolResult.builder()
                .addTextContent("Error writing script: " + e.getMessage()).build();
        }
    }

    private McpSchema.CallToolResult doRun(File scriptsDir, String name,
            Program currentProgram, GhidrAssistMCPBackend backend) {
        if (name == null) return McpSchema.CallToolResult.builder()
            .addTextContent("'name' parameter required").build();
        File f = new File(scriptsDir, normalize(name));
        if (!f.exists()) return McpSchema.CallToolResult.builder()
            .addTextContent("Script not found: " + f.getAbsolutePath()).build();

        ResourceFile sourceFile = new ResourceFile(f);
        GhidraScriptProvider provider = GhidraScriptUtil.getProvider(sourceFile);
        if (provider == null) return McpSchema.CallToolResult.builder()
            .addTextContent("No script provider for: " + name +
                " (is PyGhidra loaded for .py files?)").build();

        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        try {
            GhidraScript script = provider.getScriptInstance(sourceFile, pw);
            GhidrAssistMCPPlugin plugin = backend.getActivePlugin();
            GhidraState scriptState;
            if (plugin != null && plugin.getTool() != null) {
                scriptState = new GhidraState(plugin.getTool(),
                    plugin.getTool().getProject(), currentProgram, null, null, null);
            } else {
                scriptState = new GhidraState(null, null, currentProgram, null, null, null);
            }
            ScriptControls controls = new ScriptControls(pw, pw, TaskMonitor.DUMMY);
            script.execute(scriptState, controls);
            String output = sw.toString();
            return McpSchema.CallToolResult.builder()
                .addTextContent(output.isEmpty() ? "Script ran with no output." : output)
                .build();
        } catch (Exception e) {
            Msg.error(this, "Error running script: " + name, e);
            return McpSchema.CallToolResult.builder()
                .addTextContent("Error running script: " + e.getMessage() + "\n" + sw)
                .build();
        }
    }

    private McpSchema.CallToolResult doDelete(File scriptsDir, String name) {
        if (name == null) return McpSchema.CallToolResult.builder()
            .addTextContent("'name' parameter required").build();
        File f = new File(scriptsDir, normalize(name));
        if (!f.exists()) return McpSchema.CallToolResult.builder()
            .addTextContent("Script not found: " + f.getAbsolutePath()).build();
        if (f.delete()) {
            return McpSchema.CallToolResult.builder()
                .addTextContent("Deleted: " + f.getAbsolutePath()).build();
        } else {
            return McpSchema.CallToolResult.builder()
                .addTextContent("Could not delete: " + f.getAbsolutePath()).build();
        }
    }
}
